<?php

declare(strict_types=1);

namespace Waaseyaa\Telescope\Tests\Unit\CodifiedContext;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Waaseyaa\Telescope\CodifiedContext\CodifiedContextEntry;

#[CoversClass(CodifiedContextEntry::class)]
final class CodifiedContextEntryTest extends TestCase
{
    #[Test]
    public function constructionWithAutoGeneratedFields(): void
    {
        $entry = new CodifiedContextEntry(
            type: 'session.started',
            data: ['key' => 'value'],
            sessionId: 'sess-123',
        );

        self::assertSame('session.started', $entry->type);
        self::assertSame(['key' => 'value'], $entry->data);
        self::assertSame('sess-123', $entry->sessionId);
        self::assertNotEmpty($entry->id);
        self::assertMatchesRegularExpression('/^[0-9a-f]{32}$/', $entry->id);
        self::assertInstanceOf(\DateTimeImmutable::class, $entry->createdAt);
    }

    #[Test]
    public function constructionWithExplicitIdAndTimestamp(): void
    {
        $at = new \DateTimeImmutable('2026-01-01 00:00:00');
        $entry = new CodifiedContextEntry(
            type: 'context.loaded',
            data: [],
            sessionId: 'sess-456',
            id: 'explicit-id-abc',
            createdAt: $at,
        );

        self::assertSame('explicit-id-abc', $entry->id);
        self::assertSame($at, $entry->createdAt);
    }

    #[Test]
    public function toArrayIncludesAllFields(): void
    {
        $at = new \DateTimeImmutable('2026-03-12 10:00:00');
        $entry = new CodifiedContextEntry(
            type: 'drift.detected',
            data: ['score' => 75],
            sessionId: 'sess-789',
            id: 'test-id',
            createdAt: $at,
        );

        $arr = $entry->toArray();

        self::assertSame('test-id', $arr['id']);
        self::assertSame('drift.detected', $arr['type']);
        self::assertSame(['score' => 75], $arr['data']);
        self::assertSame('sess-789', $arr['session_id']);
        self::assertArrayHasKey('created_at', $arr);
    }

    #[Test]
    public function fromArrayRoundTrip(): void
    {
        $at = new \DateTimeImmutable('2026-03-12 10:00:00.000000');
        $entry = new CodifiedContextEntry(
            type: 'validation.completed',
            data: ['drift_score' => 10],
            sessionId: 'sess-round',
            id: 'round-trip-id',
            createdAt: $at,
        );

        $arr = $entry->toArray();
        $restored = CodifiedContextEntry::fromArray($arr);

        self::assertSame($entry->id, $restored->id);
        self::assertSame($entry->type, $restored->type);
        self::assertSame($entry->data, $restored->data);
        self::assertSame($entry->sessionId, $restored->sessionId);
        self::assertSame(
            $entry->createdAt->format('Y-m-d H:i:s.u'),
            $restored->createdAt->format('Y-m-d H:i:s.u'),
        );
    }

    #[Test]
    public function fromArrayWithJsonEncodedData(): void
    {
        $row = [
            'id' => 'test-id',
            'type' => 'context.loaded',
            'data' => json_encode(['files' => ['/a', '/b']], JSON_THROW_ON_ERROR),
            'session_id' => 'sess-json',
            'created_at' => '2026-01-01 00:00:00.000000',
        ];

        $entry = CodifiedContextEntry::fromArray($row);

        self::assertSame(['files' => ['/a', '/b']], $entry->data);
        self::assertSame('sess-json', $entry->sessionId);
    }

    #[Test]
    public function twoEntriesHaveUniqueIds(): void
    {
        $a = new CodifiedContextEntry(type: 't', data: [], sessionId: 's');
        $b = new CodifiedContextEntry(type: 't', data: [], sessionId: 's');

        self::assertNotSame($a->id, $b->id);
    }
}
